title: Menu generico per ristorante
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: red
  mode: light
  base_font: serif
  header:
    title: Le Tre Botteghe
    logo: images/copertina.png
    logo_alt: Logo le tre botteghe
    has_primary_nav: true
    primary_nav_links:
      - label: Bar
        url: '/#BAR'
        style: link
      - label: Primi
        url: '/#PRIMI'
        style: link
      - label: Secondi
        url: '/#SECONDI'
        style: primary
      - label: Bar
        url: '/#BAR'
        style: link
      - label: Primi
        url: '/#PRIMI'
        style: link
      - label: Bar
        url: '/#BAR'
        style: link
      - label: Primi
        url: '/#PRIMI'
        style: link
      - label: Secondi
        url: '/#SECONDI'
        style: link
    has_secondary_nav: false
    secondary_nav_links:
      - label: secondi
        url: '/#primi'
    has_anncmnt: false
    sectionPagesMenu: "main"
  footer:
    logo_alt: Logo Tre Botteghe
    has_primary_nav: true
    primary_nav_links: []
    has_secondary_nav: false
    secondary_nav_links:
      - label: Terms & Conditions
        url: /terms-conditions
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/'
        style: link
        has_icon: true
        icon: twitter
        icon_position: center
        new_window: true
      - label: Facebook
        url: 'https://www.facebook.com/'
        style: link
        has_icon: true
        icon: facebook
        icon_position: center
        new_window: true
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: link
        has_icon: true
        icon: instagram
        icon_position: center
        new_window: true
      - label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: link
        has_icon: true
        icon: linkedin
        icon_position: center
        new_window: true
    content: >-
      &copy; <a href="https://alessandrooncini.netlify.app" target="_blank"
      rel="noopener">Alessandro Oncini</a>. Tutti i diritti riservati. Hai
      bisogno di un menù digitale per la tua attività? Contattami!
    logo: images/copertina.png
    has_tertiary_nav: false
  domain: 'https://menugenerico.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
